version: "3"

services: 
    web:
        container_name: lecturapp
        restart: always
        build: .
        ports:
            - "5000:3000"
        links:
          - mongo    
        
    mongo:
        container_name: mymongodb
        image: mongo
        ports: 
            - "27018:27017"
        
<<<<<<< HEAD
            
=======
            
>>>>>>> e0a7f9f8dca6674b4faa81136214c0b4b66b40a4
