//Este archivo no se utiliza porque el Docker sólo tiene un container que es la web. La base de datos está implementada en Cosmos DB de Azure.

version: "3"

services: 
    web:
        container_name: lecturapp
        restart: always
        build: .
        ports:
            - "5000:3000"
        links:
          - mongo    
        
    mongo:
        container_name: mymongodb
        image: mongo
        ports: 
            - "27018:27017"
